/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideaendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideaendpoint/v1
// Description:
//   This is an API

#import "GTLAppideaendpointConstants.h"

#import "GTLAppideaendpointAppIdea.h"
#import "GTLAppideaendpointCollectionResponseAppIdea.h"
#import "GTLAppideaendpointKey.h"

#import "GTLQueryAppideaendpoint.h"
#import "GTLServiceAppideaendpoint.h"
