/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideaendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideaendpoint/v1
// Description:
//   This is an API

#import "GTLAppideaendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAppideaendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
