/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideaendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideaendpoint/v1
// Description:
//   This is an API

#import "GTLAppideaendpointConstants.m"

#import "GTLAppideaendpointAppIdea.m"
#import "GTLAppideaendpointCollectionResponseAppIdea.m"
#import "GTLAppideaendpointKey.m"

#import "GTLQueryAppideaendpoint.m"
#import "GTLServiceAppideaendpoint.m"
