/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideaendpointAppIdea.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideaendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAppideaendpointAppIdea (0 custom class methods, 9 custom properties)

#import "GTLAppideaendpointAppIdea.h"

#import "GTLAppideaendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLAppideaendpointAppIdea
//

@implementation GTLAppideaendpointAppIdea
@dynamic categoryId, details, key, numVotes, summary, timeEdited, timeSubmitted,
         title, userId;
@end
