/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideaendpointAppIdea.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideaendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAppideaendpointAppIdea (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAppideaendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLAppideaendpointAppIdea
//

@interface GTLAppideaendpointAppIdea : GTLObject
@property (retain) NSNumber *categoryId;  // longLongValue
@property (copy) NSString *details;
@property (retain) GTLAppideaendpointKey *key;
@property (retain) NSNumber *numVotes;  // intValue
@property (copy) NSString *summary;
@property (retain) NSNumber *timeEdited;  // longLongValue
@property (retain) NSNumber *timeSubmitted;  // longLongValue
@property (copy) NSString *title;
@property (retain) NSNumber *userId;  // longLongValue
@end
