/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideaendpointCollectionResponseAppIdea.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideaendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAppideaendpointCollectionResponseAppIdea (0 custom class methods, 2 custom properties)

#import "GTLAppideaendpointCollectionResponseAppIdea.h"

#import "GTLAppideaendpointAppIdea.h"

// ----------------------------------------------------------------------------
//
//   GTLAppideaendpointCollectionResponseAppIdea
//

@implementation GTLAppideaendpointCollectionResponseAppIdea
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAppideaendpointAppIdea class]
                                forKey:@"items"];
  return map;
}

@end
