/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryAppideaendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideaendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAppideaendpoint (6 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAppideaendpointAppIdea;

@interface GTLQueryAppideaendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *cursor;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) NSInteger limit;
@property (assign) long long userId;
@property (assign) NSInteger vote;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryAppideaendpoint object.

// Method: appideaendpoint.getAppIdea
//  Authorization scope(s):
//   kGTLAuthScopeAppideaendpointUserinfoEmail
// Fetches a GTLAppideaendpointAppIdea.
+ (id)queryForGetAppIdeaWithIdentifier:(long long)identifier;

// Method: appideaendpoint.insertAppIdea
//  Authorization scope(s):
//   kGTLAuthScopeAppideaendpointUserinfoEmail
// Fetches a GTLAppideaendpointAppIdea.
+ (id)queryForInsertAppIdeaWithObject:(GTLAppideaendpointAppIdea *)object;

// Method: appideaendpoint.listAppIdea
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeAppideaendpointUserinfoEmail
// Fetches a GTLAppideaendpointCollectionResponseAppIdea.
+ (id)queryForListAppIdea;

// Method: appideaendpoint.listAppIdeasByUserId
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeAppideaendpointUserinfoEmail
// Fetches a GTLAppideaendpointCollectionResponseAppIdea.
+ (id)queryForListAppIdeasByUserIdWithUserId:(long long)userId
                                        vote:(NSInteger)vote;

// Method: appideaendpoint.removeAppIdea
//  Authorization scope(s):
//   kGTLAuthScopeAppideaendpointUserinfoEmail
+ (id)queryForRemoveAppIdeaWithIdentifier:(long long)identifier;

// Method: appideaendpoint.updateAppIdea
//  Authorization scope(s):
//   kGTLAuthScopeAppideaendpointUserinfoEmail
// Fetches a GTLAppideaendpointAppIdea.
+ (id)queryForUpdateAppIdeaWithObject:(GTLAppideaendpointAppIdea *)object;

@end
