/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideavoteendpointAppIdeaVote.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAppideavoteendpointAppIdeaVote (0 custom class methods, 4 custom properties)

#import "GTLAppideavoteendpointAppIdeaVote.h"

#import "GTLAppideavoteendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLAppideavoteendpointAppIdeaVote
//

@implementation GTLAppideavoteendpointAppIdeaVote
@dynamic appIdeaId, key, userId, vote;
@end
