/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideavoteendpointCollectionResponseAppIdeaVote.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAppideavoteendpointCollectionResponseAppIdeaVote (0 custom class methods, 2 custom properties)

#import "GTLAppideavoteendpointCollectionResponseAppIdeaVote.h"

#import "GTLAppideavoteendpointAppIdeaVote.h"

// ----------------------------------------------------------------------------
//
//   GTLAppideavoteendpointCollectionResponseAppIdeaVote
//

@implementation GTLAppideavoteendpointCollectionResponseAppIdeaVote
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAppideavoteendpointAppIdeaVote class]
                                forKey:@"items"];
  return map;
}

@end
