/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideavoteendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API

#import "GTLAppideavoteendpointConstants.m"

#import "GTLAppideavoteendpointAppIdeaVote.m"
#import "GTLAppideavoteendpointAppIdeaVoteCollection.m"
#import "GTLAppideavoteendpointCollectionResponseAppIdeaVote.m"
#import "GTLAppideavoteendpointKey.m"

#import "GTLQueryAppideavoteendpoint.m"
#import "GTLServiceAppideavoteendpoint.m"
