/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideavoteendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API

#import "GTLAppideavoteendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAppideavoteendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
