/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideavoteendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API

#import "GTLAppideavoteendpointConstants.h"

#import "GTLAppideavoteendpointAppIdeaVote.h"
#import "GTLAppideavoteendpointAppIdeaVoteCollection.h"
#import "GTLAppideavoteendpointCollectionResponseAppIdeaVote.h"
#import "GTLAppideavoteendpointKey.h"

#import "GTLQueryAppideavoteendpoint.h"
#import "GTLServiceAppideavoteendpoint.h"
