/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideavoteendpointAppIdeaVote.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAppideavoteendpointAppIdeaVote (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAppideavoteendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLAppideavoteendpointAppIdeaVote
//

@interface GTLAppideavoteendpointAppIdeaVote : GTLObject
@property (retain) NSNumber *appIdeaId;  // longLongValue
@property (retain) GTLAppideavoteendpointKey *key;
@property (retain) NSNumber *userId;  // longLongValue
@property (retain) NSNumber *vote;  // intValue
@end
