/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAppideavoteendpointAppIdeaVoteCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAppideavoteendpointAppIdeaVoteCollection (0 custom class methods, 1 custom properties)

#import "GTLAppideavoteendpointAppIdeaVoteCollection.h"

#import "GTLAppideavoteendpointAppIdeaVote.h"

// ----------------------------------------------------------------------------
//
//   GTLAppideavoteendpointAppIdeaVoteCollection
//

@implementation GTLAppideavoteendpointAppIdeaVoteCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAppideavoteendpointAppIdeaVote class]
                                forKey:@"items"];
  return map;
}

@end
