/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryAppideavoteendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   appideavoteendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAppideavoteendpoint (6 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAppideavoteendpointAppIdeaVote;

@interface GTLQueryAppideavoteendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (assign) long long appIdeaId;
@property (copy) NSString *cursor;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) NSInteger limit;
@property (assign) NSInteger vote;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryAppideavoteendpoint object.

// Method: appideavoteendpoint.getAppIdeaVote
//  Authorization scope(s):
//   kGTLAuthScopeAppideavoteendpointUserinfoEmail
// Fetches a GTLAppideavoteendpointAppIdeaVote.
+ (id)queryForGetAppIdeaVoteWithIdentifier:(long long)identifier;

// Method: appideavoteendpoint.getVotesByAppIdea
//  Authorization scope(s):
//   kGTLAuthScopeAppideavoteendpointUserinfoEmail
// Fetches a GTLAppideavoteendpointAppIdeaVoteCollection.
+ (id)queryForGetVotesByAppIdeaWithAppIdeaId:(long long)appIdeaId
                                        vote:(NSInteger)vote;

// Method: appideavoteendpoint.insertAppIdeaVote
//  Authorization scope(s):
//   kGTLAuthScopeAppideavoteendpointUserinfoEmail
// Fetches a GTLAppideavoteendpointAppIdeaVote.
+ (id)queryForInsertAppIdeaVoteWithObject:(GTLAppideavoteendpointAppIdeaVote *)object;

// Method: appideavoteendpoint.listAppIdeaVote
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeAppideavoteendpointUserinfoEmail
// Fetches a GTLAppideavoteendpointCollectionResponseAppIdeaVote.
+ (id)queryForListAppIdeaVote;

// Method: appideavoteendpoint.removeAppIdeaVote
//  Authorization scope(s):
//   kGTLAuthScopeAppideavoteendpointUserinfoEmail
+ (id)queryForRemoveAppIdeaVoteWithIdentifier:(long long)identifier;

// Method: appideavoteendpoint.updateAppIdeaVote
//  Authorization scope(s):
//   kGTLAuthScopeAppideavoteendpointUserinfoEmail
// Fetches a GTLAppideavoteendpointAppIdeaVote.
+ (id)queryForUpdateAppIdeaVoteWithObject:(GTLAppideavoteendpointAppIdeaVote *)object;

@end
