/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryUserendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryUserendpoint (7 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLUserendpointUser;

@interface GTLQueryUserendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *apiKey;
@property (copy) NSString *cursor;
@property (copy) NSString *displayName;
@property (copy) NSString *email;
@property (copy) NSString *firstName;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (copy) NSString *lastName;
@property (assign) NSInteger limit;
@property (copy) NSString *password;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryUserendpoint object.

// Method: userendpoint.getCurrentUser
//  Authorization scope(s):
//   kGTLAuthScopeUserendpointUserinfoEmail
// Fetches a GTLUserendpointUser.
+ (id)queryForGetCurrentUserWithApiKey:(NSString *)apiKey;

// Method: userendpoint.insertNewUser
//  Authorization scope(s):
//   kGTLAuthScopeUserendpointUserinfoEmail
// Fetches a GTLUserendpointAuthResponse.
+ (id)queryForInsertNewUserWithEmail:(NSString *)email
                            password:(NSString *)password
                           firstName:(NSString *)firstName
                            lastName:(NSString *)lastName
                         displayName:(NSString *)displayName;

// Method: userendpoint.insertUser
//  Authorization scope(s):
//   kGTLAuthScopeUserendpointUserinfoEmail
// Fetches a GTLUserendpointUser.
+ (id)queryForInsertUserWithObject:(GTLUserendpointUser *)object;

// Method: userendpoint.listUser
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeUserendpointUserinfoEmail
// Fetches a GTLUserendpointCollectionResponseUser.
+ (id)queryForListUser;

// Method: userendpoint.logInUser
//  Authorization scope(s):
//   kGTLAuthScopeUserendpointUserinfoEmail
// Fetches a GTLUserendpointAuthResponse.
+ (id)queryForLogInUserWithEmail:(NSString *)email
                        password:(NSString *)password;

// Method: userendpoint.removeUser
//  Authorization scope(s):
//   kGTLAuthScopeUserendpointUserinfoEmail
+ (id)queryForRemoveUserWithIdentifier:(long long)identifier;

// Method: userendpoint.updateUser
//  Authorization scope(s):
//   kGTLAuthScopeUserendpointUserinfoEmail
// Fetches a GTLUserendpointUser.
+ (id)queryForUpdateUserWithObject:(GTLUserendpointUser *)object;

@end
