/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointAuthResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointAuthResponse (0 custom class methods, 4 custom properties)

#import "GTLUserendpointAuthResponse.h"

#import "GTLUserendpointUser.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointAuthResponse
//

@implementation GTLUserendpointAuthResponse
@dynamic apiKey, error, inError, user;
@end
