/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointCollectionResponseUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointCollectionResponseUser (0 custom class methods, 2 custom properties)

#import "GTLUserendpointCollectionResponseUser.h"

#import "GTLUserendpointUser.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointCollectionResponseUser
//

@implementation GTLUserendpointCollectionResponseUser
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLUserendpointUser class]
                                forKey:@"items"];
  return map;
}

@end
