/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API

#import "GTLUserendpointConstants.m"

#import "GTLUserendpointAuthResponse.m"
#import "GTLUserendpointCollectionResponseUser.m"
#import "GTLUserendpointKey.m"
#import "GTLUserendpointUser.m"

#import "GTLQueryUserendpoint.m"
#import "GTLServiceUserendpoint.m"
