/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUser (0 custom class methods, 11 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLUserendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUser
//

@interface GTLUserendpointUser : GTLObject
@property (copy) NSString *address;
@property (copy) NSString *displayName;
@property (copy) NSString *email;
@property (copy) NSString *firstName;
@property (retain) GTLDateTime *insertedDate;
@property (retain) GTLUserendpointKey *key;
@property (copy) NSString *lastName;
@property (copy) NSString *password;
@property (copy) NSString *phone;
@property (copy) NSString *secondaryEmail;
@property (retain) GTLDateTime *updatedDate;
@end
