/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUser (0 custom class methods, 11 custom properties)

#import "GTLUserendpointUser.h"

#import "GTLUserendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUser
//

@implementation GTLUserendpointUser
@dynamic address, displayName, email, firstName, insertedDate, key, lastName,
         password, phone, secondaryEmail, updatedDate;
@end
